### ISSUE TITLE
Add a label on each policy with their control number

### ISSUE THREAD

**Issue by craigbox** [kubescape/cel-admission-library#40]
In reviewing a blog post, [@sftim wrote](https://github.com/kubernetes/website/pull/40174#discussion_r1151585180):

> ```apiVersion: admissionregistration.k8s.io/v1alpha1
> kind: ValidatingAdmissionPolicy
> metadata:
>   name: "kubescape-c-0017-deny-resources-with-mutable-container-filesystem"
> ```
> I'd expect to see a label here where the value was "C-0017". Maybe an annotation with a link to the Kubescape page about that control.
> 
> This is more feedback on the library itself, and not on the article.

We should add labels like so.

**Comment by XDRAGON2002** [comment]
@craigbox could you confirm once if the field names are appropriate enough? I've used `controlId` and `controlUrl` respectively.
