### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Cajga** [kubescape/cel-admission-library#53]
Hi guys,

we started to work on a similar, community driven, open source repo (VAP library + test framework for VAP) ourselves (just designing the test framework with few policy examples). We would like to put more focus on self-contained policies and parameter validation and also to have a "security platform independent library".

Your repo contains many well written examples. We wonder if we could reuse some of them and base some of our policies (and maybe the test framework) on yours. Could you please clarify the license that you have for this repo.

**Comment by slashben** [comment]
Hey @Cajga , 

Sorry for missing the license. I have added it, feel free to reuse 😄 

Ben

**Comment by Cajga** [comment]
That is nice, thanks a lot.
